### PR TITLE
Fix parity between HTTPs and gRPC pub/sub

### LINKED ISSUE #343: v3.0.0 deprecate req.body.data in favor of req.body on pub/sub
## Describe the proposal

We need to deprecate returning req.body.data in favor of req.body on the pubsub API to support components that don't utilize req.body.data

https://github.com/dapr/js-sdk/blob/main/src/implementation/Server/HTTPServer/HTTPServerImpl.ts#L91

### PR DESCRIPTION
**Pull request by shubham1172**
# Description

Main theme of this PR is to align the HTTPs and gRPC pub/sub subscription. Both of them should return the data in the same way for both normal and rawPayload modes.

Other fixes
1. Fix metadata setting in gRPC pubsub and binding
1. Move pub/sub tests to e2e/common and delete them from e2e/http and e2e/grpc
1. Introduce redis for testing e2e
1. Enhancements to serializer (which will be superseded by #381)

## Issue reference

Closes #343

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [X] Code compiles correctly
- [X] Created/updated tests
- [ ] Extended the documentation

### CODE REVIEW

File: src/implementation/Server/HTTPServer/HTTPServerImpl.ts [hunk 1]
```diff
@@ -40,6 +37,38 @@ export default class HTTPServerImpl {
...
+   * @param req HTTP Request
+   * @returns Data from the request body.
+   */
+  extractSubscribeDataFromRequest(req: any): any {
+    const payload = req.body ?? "";
+
+    // The payload should be an object with string keys and any values.
+    // If data is present in req.body.data, use that as-is.
+    // Else, data is present in req.body.data_base64, and decode it from base64.
+    if (payload instanceof Object && !(payload instanceof Array || payload instanceof Buffer)) {
```
Comment (XavierGeerinck) [inline src/implementation/Server/HTTPServer/HTTPServerImpl.ts:53]: Change to a negate, instead of `if (payload instanceof Object && !(payload instanceof Array || payload instanceof Buffer))` let's maybe use `if (!(payload instanceof Object) || payload instanceof Array || payload instanceof Buffer)` this way we can early return removing an extra identation

File: src/implementation/Server/HTTPServer/HTTPServerImpl.ts [hunk 2]
```diff
@@ -40,6 +37,38 @@ export default class HTTPServerImpl {
...
+      if (payload.data) {
```
Comment (XavierGeerinck) [inline src/implementation/Server/HTTPServer/HTTPServerImpl.ts:54]: Let's not use an else if here seeing that we are returning?

File: src/implementation/Server/HTTPServer/HTTPServerImpl.ts [hunk 3]
```diff
@@ -40,6 +37,38 @@ export default class HTTPServerImpl {
...
+        return payload.data;
+      } else if (payload.data_base64 && typeof payload.data_base64 === "string") {
```
Comment (XavierGeerinck) [inline src/implementation/Server/HTTPServer/HTTPServerImpl.ts:56]: Change to `if` then

File: src/implementation/Server/HTTPServer/HTTPServerImpl.ts [hunk 4]
```diff
@@ -40,6 +37,38 @@ export default class HTTPServerImpl {
...
+        const parsedBase64 = Buffer.from(payload.data_base64, "base64").toString();
+        try {
```
Comment (XavierGeerinck) [inline src/implementation/Server/HTTPServer/HTTPServerImpl.ts:58]: Newline above

File: test/unit/main/HttpServerImpl.test.ts [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+
+import express from "express";
+import HTTPServerImpl from "../../../src/implementation/Server/HTTPServer/HTTPServerImpl";
+
+describe("HttpServerImpl", () => {
+  const server = new HTTPServerImpl(express());
+  describe("extractSubscribeDataFromRequest", () => {
```
Comment (XavierGeerinck) [inline test/unit/main/HttpServerImpl.test.ts:19]: nit: newline

File: test/unit/main/HttpServerImpl.test.ts [hunk 6]
```diff
@@ -0,0 +1,84 @@
...
+    it("should return string data correctly from req.body.data", () => {
+      const req = {
+        body: {
+          data: "Hello, world!",
+        },
+      } as any;
+      const data = server.extractSubscribeDataFromRequest(req);
+      expect(data).toEqual("Hello, world!");
+    });
+    it("should return object data correctly from req.body.data", () => {
```
Comment (XavierGeerinck) [inline test/unit/main/HttpServerImpl.test.ts:29]: nit: newline

File: test/unit/main/HttpServerImpl.test.ts [hunk 7]
```diff
@@ -0,0 +1,84 @@
...
+            foo: "bar",
+          },
+        },
+      } as any;
+      const data = server.extractSubscribeDataFromRequest(req);
+      expect(data).toEqual({
+        foo: "bar",
+      });
+    });
+    it("should return data instead of data_base64 if former is present", () => {
```
Comment (XavierGeerinck) [inline test/unit/main/HttpServerImpl.test.ts:42]: nit: newline

File: test/unit/main/HttpServerImpl.test.ts [hunk 8]
```diff
@@ -0,0 +1,84 @@
...
+      const req = {
+        body: {
+          data: "Hello, world!",
+          data_base64: "SGVsbG8sIHdvcmxkIQ==",
+        },
+      } as any;
+      const data = server.extractSubscribeDataFromRequest(req);
+      expect(data).toEqual("Hello, world!");
+    });
+    it("should return data_base64 decoded if data is not present", () => {
```
Comment (XavierGeerinck) [inline test/unit/main/HttpServerImpl.test.ts:52]: nit: newline

File: test/unit/main/HttpServerImpl.test.ts [hunk 9]
```diff
@@ -0,0 +1,84 @@
...
+      const req = {
+        body: {
+          data_base64: "SGVsbG8sIHdvcmxkIQ==",
+        },
+      } as any;
+      const data = server.extractSubscribeDataFromRequest(req);
+      expect(data).toEqual("Hello, world!");
+    });
+    it("should parse data_base64 as JSON", () => {
```
Comment (XavierGeerinck) [inline test/unit/main/HttpServerImpl.test.ts:61]: nit: newline

File: test/unit/main/HttpServerImpl.test.ts [hunk 10]
```diff
@@ -0,0 +1,84 @@
...
+        body: {
+          data_base64: "eyJmb28iOiAiYmFyIn0=",
+        },
+      } as any;
+      const data = server.extractSubscribeDataFromRequest(req);
+      expect(data).toEqual({
+        foo: "bar",
+      });
+    });
+    it("should return the req.body if data or data_base64 are not present", () => {
```
Comment (XavierGeerinck) [inline test/unit/main/HttpServerImpl.test.ts:72]: nit: newline

File: test/unit/main/HttpServerImpl.test.ts [hunk 11]
```diff
@@ -0,0 +1,84 @@
...
+      expect(data).toEqual("Hello, world!");
+    });
+    it("should parse data_base64 as JSON", () => {
+      const req = {
+        body: {
+          data_base64: "eyJmb28iOiAiYmFyIn0=",
+        },
+      } as any;
+      const data = server.extractSubscribeDataFromRequest(req);
+      expect(data).toEqual({
```
Comment (XavierGeerinck) [inline test/unit/main/HttpServerImpl.test.ts:68]: nit: newline

File: test/unit/main/HttpServerImpl.test.ts [hunk 12]
```diff
@@ -0,0 +1,84 @@
...
+      const data = server.extractSubscribeDataFromRequest(req);
+      expect(data).toEqual("Hello, world!");
+    });
+    it("should parse data_base64 as JSON", () => {
+      const req = {
+        body: {
+          data_base64: "eyJmb28iOiAiYmFyIn0=",
+        },
+      } as any;
+      const data = server.extractSubscribeDataFromRequest(req);
```
Comment (XavierGeerinck) [inline test/unit/main/HttpServerImpl.test.ts:67]: nit: newline

File: test/unit/main/HttpServerImpl.test.ts [hunk 13]
```diff
@@ -0,0 +1,84 @@
...
+      expect(data).toEqual("Hello, world!");
+    });
+    it("should return data_base64 decoded if data is not present", () => {
+      const req = {
+        body: {
+          data_base64: "SGVsbG8sIHdvcmxkIQ==",
+        },
+      } as any;
+      const data = server.extractSubscribeDataFromRequest(req);
```
Comment (XavierGeerinck) [inline test/unit/main/HttpServerImpl.test.ts:58]: nit: newline

File: test/unit/main/HttpServerImpl.test.ts [hunk 14]
```diff
@@ -0,0 +1,84 @@
...
+      expect(data).toEqual("Hello, world!");
```
Comment (XavierGeerinck) [inline test/unit/main/HttpServerImpl.test.ts:59]: nit: newline

File: test/unit/main/HttpServerImpl.test.ts [hunk 15]
```diff
@@ -0,0 +1,84 @@
...
+      });
+    });
+    it("should return the req.body if data or data_base64 are not present", () => {
+      const req = {
+        body: {
+          foo: "bar",
+        },
+      } as any;
+      const data = server.extractSubscribeDataFromRequest(req);
+      expect(data).toEqual({
```
Comment (XavierGeerinck) [inline test/unit/main/HttpServerImpl.test.ts:79]: nit: newline

File: test/unit/main/HttpServerImpl.test.ts [hunk 16]
```diff
@@ -0,0 +1,84 @@
...
+        foo: "bar",
+      });
+    });
+    it("should return the req.body if data or data_base64 are not present", () => {
+      const req = {
+        body: {
+          foo: "bar",
+        },
+      } as any;
+      const data = server.extractSubscribeDataFromRequest(req);
```
Comment (XavierGeerinck) [inline test/unit/main/HttpServerImpl.test.ts:78]: nit: newline

File: test/unit/utils/Client.util.test.ts [hunk 17]
```diff
@@ -22,30 +22,27 @@ import { Map } from "google-protobuf";
...
+      const m = new Map<string, string>([]);
       const metadata = {
         key1: "value1",
         key2: "value2",
       };
-      const grpcMetadata = createGRPCMetadata(metadata);
-      expect(grpcMetadata.get("key1")).toEqual(["value1"]);
-      expect(grpcMetadata.get("key2")).toEqual(["value2"]);
+      addMetadataToMap(m, metadata);
+      expect(m.get("key1")).toEqual("value1");
```
Comment (XavierGeerinck) [inline test/unit/utils/Client.util.test.ts:32]: nit: newline

File: test/unit/utils/Client.util.test.ts [hunk 18]
```diff
@@ -22,30 +22,27 @@ import { Map } from "google-protobuf";
...
+    it("should add values to Map", () => {
+      const m = new Map<string, string>([]);
       const metadata = {
         key1: "value1",
         key2: "value2",
       };
-      const grpcMetadata = createGRPCMetadata(metadata);
-      expect(grpcMetadata.get("key1")).toEqual(["value1"]);
-      expect(grpcMetadata.get("key2")).toEqual(["value2"]);
+      addMetadataToMap(m, metadata);
```
Comment (XavierGeerinck) [inline test/unit/utils/Client.util.test.ts:31]: nit: newline

**Review by XavierGeerinck — CHANGES_REQUESTED** [review]

File: src/implementation/Client/GRPCClient/binding.ts [hunk 19]
```diff
@@ -26,19 +27,22 @@ export default class GRPCClientBinding implements IClientBinding {
...
-  async send(bindingName: string, operation: string, data: any, metadata: object = {}): Promise<object> {
+  async send(bindingName: string, operation: string, data: any, metadata: KeyValueType = {}): Promise<object> {
     const msgService = new InvokeBindingRequest();
     msgService.setName(bindingName);
     msgService.setOperation(operation);
-    msgService.setData(SerializerUtil.serializeGrpc(data).serializedData);
 
-    const grpcMetadata = createGRPCMetadata(metadata);
-    const client = await this.client.getClient();
+    if (data) {
```
[the remark this answers is not in the document]
Comment (shubham1172) [reply src/implementation/Client/GRPCClient/binding.ts:36]: Nope, I could not figure out how to unit test a gRPC mock just yet (can be a separate PR). As for e2e, do you have any test idea?

File: src/implementation/Server/HTTPServer/HTTPServerImpl.ts [hunk 20]
```diff
@@ -40,6 +37,45 @@ export default class HTTPServerImpl {
...
   }
 
+  /**
+   * Extracts data from the subscribe request body.
+   * Data should be present in req.body.data or req.body.data_base64 depending on the rawPayload metadata.
+   * If the data is not found, the request body is returned as-is.
+   * @param req HTTP Request
+   * @returns Data from the request body.
+   */
+  extractSubscribeDataFromRequest(req: any): any {
```
Comment (DeepanshuA) [inline src/implementation/Server/HTTPServer/HTTPServerImpl.ts:47]:
```suggestion
  extractSubscribedDataFromRequest(req: any): any {
```

or 
```suggestion
  extractDataFromSubscribeRequest(req: any): any {
```

File: test/components/common/pubsub-redis.yaml [hunk 21]
```diff
@@ -0,0 +1,31 @@
...
+  type: pubsub.redis
+  version: v1
+  metadata:
+    - name: redisHost
+      value: localhost:6379
+    - name: redisPassword
+      value: ""
+    - name: consumerID
+      value: "myGroup"
+    - name: enableTLS
```
Comment (DeepanshuA) [inline test/components/common/pubsub-redis.yaml:30]: nit: `enableTLS` is false by default, can be omitted here

**Review by DeepanshuA — DISMISSED** [review]

**Review by XavierGeerinck — CHANGES_REQUESTED** [review]

File: src/implementation/Server/HTTPServer/HTTPServerImpl.ts [hunk 22]
```diff
@@ -40,6 +37,45 @@ export default class HTTPServerImpl {
...
+   * Data should be present in req.body.data or req.body.data_base64 depending on the rawPayload metadata.
+   * If the data is not found, the request body is returned as-is.
+   * @param req HTTP Request
+   * @returns Data from the request body.
+   */
+  extractDataFromSubscribeRequest(req: any): any {
+    const payload = req.body ?? "";
+
+    // The payload should be an object with string keys and any values.
+    if (!(payload instanceof Object) || payload instanceof Array || payload instanceof Buffer) {
```
[the remark this answers is not in the document]
Comment (shubham1172) [reply src/implementation/Server/HTTPServer/HTTPServerImpl.ts:51]: Good catch, added!

File: src/implementation/Client/GRPCClient/binding.ts (hunk 19 above)
[the remark this answers is not in the document]
Comment (shubham1172) [reply src/implementation/Client/GRPCClient/binding.ts:36]: I figured this out, created a custom mock and tested the `InvokeBindingRequest` creation.

**Review by XavierGeerinck — APPROVED** [review]
